# Generated by Django 5.2.5 on 2025-08-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.FloatField()),
                ('ingredients', models.TextField()),
                ('images', models.FileField(blank=True, null=True, upload_to='img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resturant.category')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resturant.menu'),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='menu_items',
            field=models.ManyToManyField(related_name='table_orders', through='Resturant.TableOrderItem', to='Resturant.menu'),
        ),
        migrations.AlterField(
            model_name='tableorderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resturant.menu'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
