# Generated by Django 5.2.5 on 2025-08-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resturant', '0002_remove_category_description_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table_reservation',
            table='table_reservation',
        ),
    ]
